version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: simulatecall-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: simulatecall
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: simulatecall_db
    ports:
      - "5429:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: armandocastro/simulatecall:latest
    container_name: simulatecall-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SERVICE_URL_APP_3000
      - DATABASE_URL=postgresql://simulatecall:secretpassword@db:5432/simulatecall_db?schema=public
      - ADMIN_TOKEN=super_secret_token_2026
      - APP_URL=$SERVICE_URL_APP
    volumes:
      # Garante que os arquivos locais da pasta uploads persistem mesmo se o container reiniciar
      - media_uploads:/app/public/uploads

volumes:
  postgres_data:
  media_uploads:
